import cv2

# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Performance settings
DETECTION_SCALE_FACTOR = 4
# --- THIS IS THE CORRECTED LINE ---
FACE_CASCADE_PATH = "assets/haarcascade_frontalface_alt.xml"
FACE_CONTROL_ZONE_PERCENT = 0.6

# --- Game Rule Settings ---
INITIAL_LIVES = 3
POINTS_PER_HIT = 10

# --- UI Settings ---
UI_FONT = cv2.FONT_HERSHEY_SIMPLEX
UI_FONT_SCALE = 1.2
UI_FONT_THICKNESS = 2
UI_COLOR = (255, 255, 255) # White
SCORE_POSITION = (30, 50)
LIVES_POSITION = (SCREEN_WIDTH - 200, 50)
GAME_OVER_POSITION = (SCREEN_WIDTH // 2 - 250, SCREEN_HEIGHT // 2)

# --- Paddle Settings ---
PADDLE_WIDTH = 200
PADDLE_HEIGHT = 25
PADDLE_COLOR = (255, 0, 0) # Blue
PADDLE_SMOOTHING = 0.08

# --- Ball Settings ---
BALL_RADIUS = 15
BALL_COLOR = (255, 255, 255) # White
BALL_INITIAL_VX = 6
BALL_INITIAL_VY = -6