import cv2

# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Performance settings
DETECTION_SCALE_FACTOR = 4
FACE_CASCADE_PATH = "assets/haarcascade_frontalface_alt.xml"
FACE_CONTROL_ZONE_PERCENT = 0.5 

# --- Game Rule Settings ---
INITIAL_LIVES = 3
POINTS_PER_HIT = 10
HITS_PER_LEVEL = 5 # Level up after 5 paddle hits
BALL_SPEED_INCREASE = 1.5

# --- UI Settings ---
UI_FONT = cv2.FONT_HERSHEY_SIMPLEX
UI_FONT_SCALE = 1.2
UI_FONT_THICKNESS = 2
UI_COLOR = (255, 255, 255) # White
SCORE_POSITION = (30, 50)
LIVES_POSITION = (SCREEN_WIDTH - 200, 50)
LEVEL_POSITION = (SCREEN_WIDTH // 2 - 100, 50)
GAME_OVER_POSITION = (SCREEN_WIDTH // 2 - 250, SCREEN_HEIGHT // 2)

# --- Paddle Settings ---
PADDLE_WIDTH = 200
PADDLE_HEIGHT = 25
PADDLE_COLOR = (255, 0, 0) # Blue
PADDLE_SMOOTHING = 0.12
PADDLE_BOUNCE_INTENSITY = 8.0

# --- Ball Settings ---
BALL_RADIUS = 15
BALL_COLOR = (255, 255, 255) # White
BALL_INITIAL_VX = 7.2
BALL_INITIAL_VY = -7.2